import { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'The Skeleton Modular Frame',
    category: 'sofas',
    price: 1899,
    rating: 4.9,
    reviews: 128,
    image: 'https://images.unsplash.com/photo-1615873968403-89e068629265?auto=format&fit=crop&w=800&q=80',
    description: 'The perfect backbone for your custom cushions. Crafted from marine-grade aluminum, this frame waits for your cover.',
    features: ['Marine-grade aluminum', 'Rust-proof', 'Fits standard 24x24 cushions'],
    inStock: true,
  },
  {
    id: '2',
    name: 'Laguna Teak Table Base',
    category: 'dining',
    price: 2200,
    rating: 4.8,
    reviews: 84,
    image: 'https://images.unsplash.com/photo-1565791380709-47e5758143d8?auto=format&fit=crop&w=800&q=80',
    description: 'A solid teak foundation for your dining experience. Just add chairs (and your favorite tablecloth).',
    features: ['Solid Grade-A Teak', 'Seats 8', 'Umbrella hole included'],
    inStock: true,
  },
  {
    id: '3',
    name: 'Bare Bones Chaise',
    category: 'loungers',
    price: 699,
    rating: 4.7,
    reviews: 215,
    image: 'https://images.unsplash.com/photo-1532323544230-7191fd51bc1b?auto=format&fit=crop&w=800&q=80',
    description: 'Designed specifically for your replacement slings. A sleek, ergonomic curve that needs your touch.',
    features: ['Adjustable backrest', 'Standard sling track', 'Powder-coated finish'],
    inStock: true,
  },
  {
    id: '4',
    name: 'Structure Fire Pit',
    category: 'accessories',
    price: 950,
    rating: 4.9,
    reviews: 340,
    image: 'https://images.unsplash.com/photo-1623626899359-235245c510a7?auto=format&fit=crop&w=800&q=80',
    description: 'The core of your patio warmth. Industrial concrete finish that pairs with any furniture cover style.',
    features: ['50,000 BTU', 'Concrete finish', 'Glass wind guard included'],
    inStock: true,
  },
  {
    id: '5',
    name: 'Essential Sectional Frame',
    category: 'sofas',
    price: 1499,
    rating: 4.6,
    reviews: 56,
    image: 'https://images.unsplash.com/photo-1662417926380-d86b7696d22f?auto=format&fit=crop&w=800&q=80',
    description: 'Deep seating geometry without the fabric. You bring the style, we provide the strength.',
    features: ['Wicker weave over aluminum', 'Clips included', 'Compact footprint'],
    inStock: false,
  },
  {
    id: '6',
    name: 'Driftwood Centerpiece',
    category: 'accessories',
    price: 450,
    rating: 4.5,
    reviews: 42,
    image: 'https://images.unsplash.com/photo-1604069468067-7c3c64e83236?auto=format&fit=crop&w=800&q=80',
    description: 'A raw, natural base that anchors your space. No cover needed for this beauty.',
    features: ['Natural driftwood', 'Tempered glass', 'Handcrafted'],
    inStock: true,
  },
  {
    id: '7',
    name: 'The Framework Chair Pair',
    category: 'dining',
    price: 499,
    rating: 4.8,
    reviews: 90,
    image: 'https://images.unsplash.com/photo-1586158291800-2665f07bba79?auto=format&fit=crop&w=800&q=80',
    description: 'High-tensile steel frames ready for your custom sling installation. The ultimate DIY finish.',
    features: ['Stackable', 'Standard sling rail', 'Powder-coated steel'],
    inStock: true,
  },
  {
    id: '8',
    name: 'Oasis Canopy Frame',
    category: 'loungers',
    price: 1299,
    rating: 5.0,
    reviews: 22,
    image: 'https://images.unsplash.com/photo-1540541338287-41700207dee6?auto=format&fit=crop&w=800&q=80',
    description: 'Just the heavy-duty frame and mechanism. You add the curtains and cushions to match your vibe.',
    features: ['Retractable mechanism', 'Round design', 'Heavy-duty steel'],
    inStock: true,
  }
];

export const CATEGORIES: { id: string; label: string }[] = [
  { id: 'all', label: 'All Frames' },
  { id: 'sofas', label: 'Sofa Frames' },
  { id: 'dining', label: 'Dining Bases' },
  { id: 'loungers', label: 'Lounger Rails' },
  { id: 'accessories', label: 'Hardscaping' },
];